const types = {
    CREATE_ACCOUNT_SUCCESS:"CREATE_ACCOUNT_SUCCESS",
    CREATE_ACCOUNT_FAILED:"CREATE_ACCOUNT_FAILED",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",
    AUTH_COMMON_ERROR:"AUTH_COMMON_ERROR",
    REQUESET_RESET_PASS_SUCCESS: "REQUESET_RESET_PASS_SUCCESS",
    REQUESET_RESET_PASS_FAILED: "REQUESET_RESET_PASS_FAILED",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILED: " RESET_PASSWORD_FAILED",
    LOGOUT: "LOGOUT",
    RESEND_VERIFICATION_LINK_SUCCESS :"RESEND_VERIFICATION_LINK",
    RESEND_VERIFICATION_LINK_FAILED:"RESEND_VERIFICATION_LINK_FAILED",
    OTP_REQUEST_SUCCESS:"OTP_REQUEST_SUCCESS",
    OTP_REQUEST_FAILED:"OTP_REQUEST_FAILED",
    OTP_VERIFY_SUCCESS:"OTP_VERIFY_SUCCESS",
    OTP_VERIFY_FAILED:"OTP_VERIFY_FAILED",
    CLEAR_SIGN_UP:"CLEAR_SIGN_UP",
}  


module.exports = types;