import React, { useState, useEffect } from "react";
import Select from "react-select";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import { Col, Container, Row, Button, Table, Pagination } from "react-bootstrap";
import { useDispatch, useSelector } from 'react-redux';
import { list_filegenerator } from "~/store/slices/filegenerator/action";
import toast, { Toaster } from 'react-hot-toast';
import './fileGeneratorStyle.css';
import { BsArrowRight } from "react-icons/bs";
import SidebarPanel from "../../components/Sidebar/Sidebar";
import { FileNameCountry, faceBookPageList, countryLanguageData } from "~/constants/options";

function FileGeneratorlist() {
    const dispatch = useDispatch();
    const { data, api_status, isAuthenticated, totalPages } = useSelector((state: any) => state.filegenerator);
    const [spinnerloading, setSpinnerLoading] = useState(false);
    const [IsData, setIsData] = useState(false);
    const [filegeneration, setFilegeneration] = useState([]);
    const [loadFirstTime, setLoadFirstTime] = useState(true);
    const [currentPage, setCurrentPage] = useState(1);
    const [itemsPerPage] = useState(10); // Items per page


   

    useEffect(() => {
        if (loadFirstTime) {
            dispatch(list_filegenerator({ page: currentPage, limit: itemsPerPage }));
        }
    }, [dispatch, loadFirstTime, currentPage]);


    useEffect(() => {
        
        if (data && data.length > 0 && api_status === 200) {
            setIsData(true);
            setFilegeneration(data);
        } else {
            setIsData(false);
        }
    }, [data, api_status, isAuthenticated]);

    const handlePageChange = (pageNumber) => {
        setCurrentPage(pageNumber);
    };

    const renderPagination = () => (
        <Pagination>
            <Pagination.First onClick={() => handlePageChange(1)} disabled={currentPage === 1} />
            <Pagination.Prev onClick={() => handlePageChange(currentPage - 1)} disabled={currentPage === 1} />
            {Array.from({ length: totalPages }, (_, index) => (
                <Pagination.Item
                    key={index + 1}
                    active={index + 1 === currentPage}
                    onClick={() => handlePageChange(index + 1)}
                >
                    {index + 1}
                </Pagination.Item>
            ))}
            <Pagination.Next onClick={() => handlePageChange(currentPage + 1)} disabled={currentPage === totalPages} />
            <Pagination.Last onClick={() => handlePageChange(totalPages)} disabled={currentPage === totalPages} />
        </Pagination>
    );
    
    return (
        <>
            <SidebarPanel />
            <div className="content__container projects--page filegenerator--page pb-5">
                <Container fluid>
                    <Row>
                        <Col sm={12}>
                            <Table responsive striped>
                                <thead>
                                    <tr>
                                        <th>Sr.No</th>
                                        <th>File Names</th>
                                        <th>Campaign Name</th>
                                        <th>Generated By</th>
                                        <th>Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {IsData ? (
                                        filegeneration.length > 0 ? (
                                            filegeneration.map((data, index) => (
                                                <tr key={index}>
                                                    <td style={{ minWidth: "120px" }}>{index+1}.</td>
                                                    <td style={{ minWidth: "740px" }}>
                                                        {data.generated_filename && data.generated_filename.length > 0 ? (
                                                            <ul>
                                                                {data.generated_filename.map((filename, index) => (
                                                                    <li key={index}>{filename}</li>
                                                                ))}
                                                            </ul>
                                                        ) : (
                                                            <p>No files generated</p> // Handle empty case
                                                        )}
                                                    </td>
                                                    <td style={{ minWidth: "820px" }}>{data.camp_name}</td>
                                                    <td>{data.user_name}</td>
                                                    <td>{data.file_date
                                                            ? new Date(data.file_date).toLocaleDateString("en-US", {
                                                                  year: "numeric",
                                                                  month: "short",
                                                                  day: "numeric",
                                                              })
                                                            : "N/A"}</td>
                                                </tr>
                                            ))
                                        ) : (
                                            <tr>
                                                <td colSpan="5" style={{ textAlign: "center" }}>
                                                    No records found on the server
                                                </td>
                                            </tr>
                                        )
                                    ) : (
                                        <tr>
                                            <td colSpan="5" style={{ textAlign: "center" }}>
                                                Loading...
                                            </td>
                                        </tr>
                                    )}
                                </tbody>
                            </Table>
                        </Col>
                        <Col sm={12} className="d-flex justify-content-center mt-4">
                            {renderPagination()}
                        </Col>
                    </Row>
                </Container>
            </div>
        </>
    );
}

export default FileGeneratorlist;